theme: minima
markdown: kramdown
paginate: 5

# Укажите, что ваша страница будет использовать layout: default
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "default"